[core]
fsmonitor = "watchman"

[signing]
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0TH2GezEx8+zlKBqUb7rBsbmghnd1u4nX6YpQr28Zw"
sign-all = true

[signing.backends.ssh]
program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[ui]
paginate = "never"
default-command = "log"
editor = "nvim"

[user]
email = "1699281+sloanelybutsurely@users.noreply.github.com"
name = "sloane"

[revsets]
log = "trunk() | ancestors(reachable(@ | mine(), mutable()), 2) | @"
