[core]
fsmonitor = "watchman"

[signing]
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0TH2GezEx8+zlKBqUb7rBsbmghnd1u4nX6YpQr28Zw"
sign-all = true

[signing.backends.ssh]
program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[ui]
paginate = "never"
default-command = "log"
editor = "nvim"
diff.tool = ["difft", "--color=always", "$left", "$right"]

[user]
email = "git@sloanelybutsurely.com"
name = "sloane"

[revsets]
log = "trunk() | ancestors(reachable(@ | mine(), mutable()), 2) | @"

[git]
push-bookmark-prefix = "sloane/push-"
private-commits = 'wip | nocommit | dev-only'

[aliases]
rebase-bookmarks = ["rebase", "-b", "all:current ~trunk()", "-d", "main", "--skip-emptied"]

[revset-aliases]
wip = 'description(regex:"^\\[(wip|WIP|todo|TODO)\\]|(wip|WIP|todo|TODO):?")'
nocommit = 'description(regex:"^\\[(nocommit|NOCOMMIT)\\]|(nocommit|NOCOMMIT):?")'
dev-only = 'description(regex:"^\\[(dev-only|DEV-ONLY)\\]|(dev-only|DEV-ONLY):?")'
current = "(bookmarks() | wip | dev-only) & mine()"
