[Personal]
source                  = jmap+oauthbearer://sloane%40sloanelybutsurely.com@api.fastmail.com/.well-known/jmap
source-cred-cmd         = op read "op://Private/Fastmail/JMAP"
outgoing                = jmap://
default                 = Inbox
from                    = Sloane Perrault <sloane@sloanelybutsurely.com>
use-labels              = true
cache-state             = true
cache-blobs             = true
folders-sort            = Inbox
carddav-source          = https://sloane%40sloanelybutsurely.com@carddav.fastmail.com/dav/addressbooks/user/sloane@sloanelybutsurely.com/Default
carddav-source-cred-cmd = op read "op://Private/Fastmail/CardDAV"
address-book-cmd        = carddav-query -S fastmail %s

# [screen.garden]
# source          = jmap+oauthbearer://sloane%40screen.garden@api.fastmail.com/.well-known/jmap
# source-cred-cmd = op read "op://Employee/Fastmail - screen.garden/JMAP"
# outgoing        = jmap://
# default         = Inbox
# from            = Sloane Perrault <sloane@screen.garden>
# use-labels      = true
# cache-state     = true
# cache-blobs     = true
# folders-sort    = Inbox
