[personal]
source          = maildir://~/.mail
outgoing        = msmtpq -a personal
from            = Sloane Perrault <sloane@sloanelybutsurely.com>
default         = Inbox
folders-sort    = Inbox
copy-to         = Sent
check-mail-cmd  = mbsync personal

# [screen.garden]
# source          = jmap+oauthbearer://sloane%40screen.garden@api.fastmail.com/.well-known/jmap
# source-cred-cmd = op read "op://Employee/Fastmail - screen.garden/JMAP"
# outgoing        = jmap://
# default         = Inbox
# from            = Sloane Perrault <sloane@screen.garden>
# use-labels      = true
# cache-state     = true
# cache-blobs     = true
# folders-sort    = Inbox
