#!/usr/bin/env fish

if type -q fisher
  echo "fisher already installed"
else
  echo "installing fisher"
  curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source
  fisher update
end
