call plug#begin()

Plug 'tpope/vim-sensible',    { 'tag': 'v2.0' }
Plug 'tpope/vim-surround',    { 'tag': 'v2.2' }
Plug 'tpope/vim-commentary',  { 'tag': 'v1.3' }
Plug 'tpope/vim-abolish',     { 'tag': 'v1.2' }
Plug 'tpope/vim-repeat',      { 'tag': 'v1.2' }
Plug 'tpope/vim-fugitive',    { 'tag': 'v3.7' }
Plug 'tpope/vim-rhubarb'
Plug 'preservim/nerdtree',    { 'tag': '7.1.3' }

Plug 'sderev/alabaster.vim'
Plug 'vim-polyglot/vim-polyglot'

call plug#end()

set number
set relativenumber
set shiftwidth=2
set tabstop=2
set expandtab
set mouse=a
set hlsearch

set belloff=esc

let mapleader = " "

nmap ;  :
vmap ;  :
nmap q; q:
vmap q; q:

nnoremap <c-h>  <c-w>h
nnoremap <c-j>  <c-w>j
nnoremap <c-k>  <c-w>k
nnoremap <c-l>  <c-w>l

nnoremap <silent> <leader>w      :w<cr>
nnoremap <silent> <leader>q      :q<cr>

nnoremap <silent> <leader>"      :split<cr>
nnoremap <silent> <leader>%      :vsplit<cr>

nnoremap <leader>y  "+y
vnoremap <leader>y  "+y
nnoremap <leader>p  "+p
vnoremap <leader>p  "+p

function! FzyCommand(choice_command, vim_command)
  try
    let output = system(a:choice_command . " | fzy ")
  catch /Vim:Interrupt/
    " Swallow errors from ^C, allow redraw! below
  endtry
  redraw!
  if v:shell_error == 0 && !empty(output)
    exec a:vim_command . ' ' . output
  endif
endfunction

nnoremap <leader><space>  :call FzyCommand("fd -t f -H", ":e")<cr>
nnoremap <leader>/        :call FzyCommand("rg . -l -g ''", ":e")<cr>

nnoremap <leader><tab>    :NERDTreeToggle<cr>
nnoremap <leader>fl       :NERDTreeFind<cr>

set termguicolors
colorscheme alabaster-bg
