#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[fsmonitor]
backend = "watchman"

[user]
name = "sloane"
email = "git@sloanelybutsurely.com"

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID0TH2GezEx8+zlKBqUb7rBsbmghnd1u4nX6YpQr28Zw"


[[--scope]]
--when.platforms = ["macos"]
[--scope.signing]
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[[--scope]]
--when.platforms = ["linux"]
[--scope.signing]
backends.ssh.program = "/opt/1Password/op-ssh-sign"

[ui]
paginate = "never"
default-command = "log"
editor = "nvim"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
diff-editor = ":builtin"

[git]
private-commits = "wip | nocommit | dev-only"

[templates]
git_push_bookmark = '"sloane/push-" ++ change_id.short()'

[revsets]
log = "trunk() | ancestors(reachable(@ | mine(), mutable()), 2) | @"
bookmark-advance-to = "@-"

[revset-aliases]
wip = 'description(regex:"^\\[(wip|WIP|todo|TODO)\\]|(wip|WIP|todo|TODO):?")'
nocommit = 'description(regex:"^\\[(nocommit|NOCOMMIT)\\]|(nocommit|NOCOMMIT):?")'
dev-only = 'description(regex:"^\\[(dev-only|DEV-ONLY)\\]|(dev-only|DEV-ONLY):?")'
current = '(bookmarks() | wip | dev-only) & mine() & ~immutable()'
'closest_bookmark(to)' = "heads(::to & bookmarks())"

[aliases]
r = ["rebase"]
s = ["squash"]
n = ["new"]
e = ["edit"]
tug = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
echo "jj tug has been renamed to jj hoist (or jj h). please use that instead"
exit 1
"""]
h = ["hoist"]
hoist = ["bookmark", "advance"]
catchup = ["rebase", "-b", "current", "-d", "trunk()", "--skip-emptied"]
changed = ["diff", "--files-only"]
init = ["git", "init"]
fetch = ["git", "fetch"]
push = ["git", "push"]
wip = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
revset=$1
jj log --no-graph -r $revset -T 'if(description.contains("(wip)"), description, "(wip) " ++ description)' | jj desc $revset --stdin
""", ""]
unwip = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
revset=$1
jj log --no-graph -r $revset -T 'description.replace("(wip)", "").trim()' | jj desc $revset --stdin
""", ""]
sync = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
jj fetch
jj catchup
jj push --tracked
""", ""]
